---
#<% require 'marchex_helpers' %>
<%= MarchexHelpers.kitchen( driver: :ec2, platforms: [:all], chef_versions: ['latest'] ) %>

suites:
  - name: default
    run_list:
      - recipe[mchx_dk::chef_dk]
      - recipe[mchx_dk::default]
      - recipe[sudo::default]
    attributes:
      authorization:
        sudo:
          groups: ['wheel', 'sudo']
          users: ['ubuntu', 'vagrant', 'ec2-user', 'centos']
          passwordless: true
    verifier:
      name: inspec
      inspec_tests:
      - https://github.marchex.com/marchex-chef/tests_mchx_dk/archive/master.tar.gz
      # uncomment for local testing
      #- file://../../tests/tests_mchx_dk
