---
#<% require 'marchex_helpers' %>
<%= MarchexHelpers.kitchen( driver: :ec2, platforms: [:all] ) %>

suites:
  - name: default
    run_list:
      - recipe[mchx_dk::default]
    verifier:
      name: inspec
      inspec_tests:
      - https://github.marchex.com/marchex-chef/tests_mchx_dk/archive/master.tar.gz
      # uncomment for local testing
      #- file://../../tests/tests_mchx_dk
