---
driver:
  name: ec2
  aws_ssh_key_id: tools-team
  region: us-west-2
  subnet_id: subnet-2a251342
  instance_type: t2.micro
  tags:
    Name: <%= ENV['KITCHEN_INSTANCE_NAME'] || 'test kitchen instance' %>
    team: Tools
    project: chef-test-kitchen

provisioner:
  name: chef_zero
  data_path: test/shared

verifier:
  name: inspec

transport:
  ssh_key: <%= ENV['KITCHEN_EC2_SSH_KEY_PATH'] %>
  username: ubuntu
  connection_timeout:

platforms:
<% %w(12.6.0).each do |chef_version| %>
  - name: ubuntu-12.04-<%= chef_version %>
    driver:
      image_id: ami-86688bb5
    driver_config:
      provision: true
      require_chef_omnibus: <%= chef_version %>
<% end %>

suites:
  - name: default
    run_list:
      - recipe[mchx_dk::default]
    attributes:
    verifier:
      inspec_tests:
      - https://github.marchex.com/marchex-chef/tests_mchx_auditd/archive/master.tar.gz
