# Things to ignore
AllCops:
  Exclude:
    # these are vendored
    - cookbooks/**/*
    - .vendor/**/*

Metrics/LineLength:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
  # slashes: Always use slashes.
  # percent_r: Always use %r.
  # mixed: Use slashes on single-line regexes, and %r on multi-line regexes.
  AllowInnerSlashes: true

Style/HashSyntax:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/StringLiterals:
  Enabled: false

# Don't care about these for tests
Performance/Count:
  Exclude:
    - 'spec/unit/recipes/**/*.rb'

Style/AlignParameters:
  Exclude:
    - 'spec/unit/recipes/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/unit/recipes/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/unit/recipes/**/*.rb'

Style/PercentLiteralDelimiters:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
