## do not edit this file.  put changes in "Rakefile", not here.
## to override one of these tasks in your Rakefile, clear it out:
##
##   Rake::Task[:list].clear
##   desc "List all the tasks."
##   task :list do
##     puts "our tasks are secret!"
##   end

task :default => [:list]

desc "List all the tasks."
task :list do
  puts "Tasks: \n- #{Rake::Task.tasks.join("\n- ")}"
end

desc "Update config files from GitHub."
task :"config-update" do
  puts "updating Rakefile"
  sh "curl --fail --silent --connect-timeout 2 --max-time 5 -o base.rake\
    'https://github.marchex.com/raw/marchex-chef/marchex-chef-generator/master/skel/files/default/base.rake'\
    || echo '# Failed to update Rakefile.'", verbose: false
  puts "updating RuboCop"
  sh "curl --fail --silent --connect-timeout 2 --max-time 5 -o .rubocop.yml\
    'https://github.marchex.com/raw/marchex-chef/marchex-chef-generator/master/skel/files/default/rubocop.yml'\
    || echo '# Failed to update RuboCop config.'", verbose: false
  puts "updating Foodcritic"
  sh "curl --fail --silent --connect-timeout 2 --max-time 5 -o .foodcritic\
    'https://github.marchex.com/raw/marchex-chef/marchex-chef-generator/master/skel/files/default/foodcritic'\
    || echo '# Failed to update Foodcritic config.'", verbose: false
end

desc "Check for (and resolve) required dependencies."
task :check do
  Rake::Task[:"config-update"].execute
  sh "bundle check || bundle install"
end

desc "Bundle update."
task :update do
  Rake::Task[:"config-update"].execute
  sh "bundle update"
end

desc "Run chefspec tests."
task :chefspec do
  Rake::Task[:check].execute
  sh "bundle exec rspec spec"
end

desc "Run foodcritic."
task :foodcritic do
  Rake::Task[:check].execute
  sh "bundle exec foodcritic ." # runs all built-in foodcritic rules
  sh "bundle exec foodcritic . -G -t marchex_base" # marchex-specific rules
end

desc "Run rubocop."
task :rubocop do
  Rake::Task[:check].execute
  sh "bundle exec rubocop ."
end

desc "Run validation tests."
task :lint do
  Rake::Task[:"config-update"].execute
  Rake::Task[:rubocop].execute
  Rake::Task[:foodcritic].execute
end

desc "Run unit tests."
task :unit do
  Rake::Task[:lint].execute
  Rake::Task[:chefspec].execute
end

desc "Clean up build."
task :clean do
  Rake::Task[:"config-update"].execute
  # only delete lockfiles if they are not in git
  sh <<-eos, verbose: false
  bash <<'eob'
  lockfiles_to_delete=("Berksfile.lock" "Gemfile.lock")
  for lockfile in ${lockfiles_to_delete[@]}
  do
    if [[ -e "$lockfile" ]]; then
      git ls-files ${lockfile} | grep . >/dev/null
      err=$?
      if [[ "$err" != 0 ]]; then
        echo "deleting $lockfile"
        set -e
        rm "$lockfile"
        set +e
      fi
    fi
  done
  exit 0
  eob
  eos
end

desc "Really clean up build."
task :realclean do
  Rake::Task[:clean].execute
  sh 'rm -rf .vendor'
end
